### ISSUE TITLE
gofiles: gofiles.Write sometimes fails if no go.mod file exists

### ISSUE THREAD

**Issue by tabboud** [nmiyake/pkg#24]
I am seeing some flaky test cases where `gofiles.Write()` will fail if a go.mod file cannot be found. This is currently happening on distgo when upgrading to gofiles v1.2.0. distgo specifically exposes a public test function `RunAssetDistTest` which uses gofiles ([link](https://github.com/palantir/distgo/blob/77a359ef81a8375609ea07077ea96d73aee808cd/dister/distertester/distertester.go#L101-L102)) internally to write built-in files and user specified files. The former (built-in specs) are failing on some internal tests due to failing to find the go.mod file.

PR: https://github.com/palantir/distgo/pull/226
CircleCI repro: https://app.circleci.com/pipelines/github/palantir/distgo/447/workflows/b22bad69-5f64-4018-9f41-60355142c1f2/jobs/2326/steps

I tried this out locally on a separate repo that builds a godel asset and am able to repro with the following:

```go
func TestWriteGoFiles(t *testing.T) {
	_, err := gofiles.Write(t.TempDir(), []gofiles.GoFileSpec{
		{
			RelPath: "godelw",
			Src:     "// placeholder",
		},
	})
	require.NoError(t, err)
}
```
Results in:
```
--- FAIL: TestWriteGoFiles (0.02s)
    files_test.go:105:
                Error Trace:    files_test.go:105
                Error:          Received unexpected error:
                                err: exit status 1: stderr: go: go.mod file not found in current directory or any parent directory; see 'go help modules'
                Test:           TestWriteGoFiles
```

**Comment by tabboud** [comment]
## Possible Solutions

We can require that the `[]GoFileSpec` contain a valid go project structure with `go.mod` files for each defined module. To enforce this, we can just retain the same behavior, rather than try to understand the file structure and defer to `packages.Load` to fail when it's not valid. All we need to do is update the godoc.

Then we can introduce another function which just writes out the files and only returns an error, unlike `Write` which returns the files that were written + an error. Something like this:
```go
func WriteRaw(dir string, files []GoFileSpec) error {
	_, err := writeInternal(dir, files)
	return err
}
```

Both functions can then delegate to an internal write which handles writing the files to disk
```go
func writeInternal(dir string, files []GoFileSpec) (map[string]GoFile, error) {
	dir, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}

	goFiles := make(map[string]GoFile, len(files))
	for _, currFile := range files {
        // write files
        // update goFiles map
	}
	return goFiles, nil
}
```
Based on a sourcegraph search most usages ignore the returned map of go files and only assert the error anyways, so I don't think this would be a crazy change.
https://sourcegraph.com/search?q=gofiles.Write

**Comment by nmiyake** [comment]
Thanks for tracking this down and proposing a solution!

However, in this case, I actually think that the consumer is incorrect here (I know that I'm the one who likely wrote that consuming code, but still believe this to be true :). The whole purpose of the `gofiles` package is to write Go files and get the import path back. In the case of the consuming code here, I would just update it to be a helper function that loops through and writes the files at those paths.

It's likely true that the addition of modules means that code that used to just use `gofiles.Write` to write non-Go files worked fine may now fail, but I don't think that's necessarily wrong (and even with this approach we'd need to change the callers anyway, so don't think that it buys us much).

**Comment by tabboud** [comment]
I am in-line with the proposal above. I updated distgo with what you recommended so we should be fully unblocked to take upgrades again. 
Going forward if a project wants to write files via `gofiles.Write` they need to ensure there is a valid go project structure with a declared `go.mod` file otherwise they should do something similar to what we did in distgo.
